name: Hello-World-in-the-Cloud CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and pull last commit
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    #- name: Initialize Terraform
    #  run: terraform init

    - name: Validate config files
      run: terraform validate

    - name: Create execution plan
      run: terraform plan -out=tfplan

    - name: Execute plan
      run: terraform apply -input=false tfplan
      env:
        TF_APPLY: "true"
